os:
  - linux

language: rust

rust:
  - nightly
  - stable

addons:
    postgresql: "9.5"
    apt:
        packages:
            - postgresql-client

services:
    - postgresql
    - mysql

before_script:
    - ./gather-prerequisites.sh
    - ./execute-data-import.sh



script:
    - cargo test --features "with-postgres with-sqlite"
    - cargo test --features "with-postgres"
    - cargo test --features "with-sqlite"
